package dev.anshdixit.prism.cashflow;

import java.util.List;

/**
 * Categories a raw bank transaction is mapped to by semantic similarity (pgvector k-NN against exemplar
 * descriptions). Each category carries the exemplar phrases that are embedded and stored at start-up.
 */
public enum TransactionCategory {
    INCOME_PAYROLL(Kind.INCOME, "ACH CREDIT PAYROLL", "DIRECT DEPOSIT SALARY", "PAYROLL DEP", "EMPLOYER PAYROLL ACH", "SALARY CREDIT"),
    INCOME_GIG(Kind.INCOME, "UBER TECHNOLOGIES DIRECT DEP", "DOORDASH INC PAYOUT", "LYFT INC PAYOUT", "INSTACART PAYMENT", "UPWORK ESCROW PAYOUT", "FIVERR PAYOUT"),
    INCOME_BENEFIT(Kind.INCOME, "SSA TREAS 310 XXSOC SEC", "STATE UNEMPLOYMENT BENEFIT", "IRS TREAS 310 TAX REF", "VA BENEFIT DEPOSIT"),
    INCOME_TRANSFER(Kind.INCOME, "VENMO CASHOUT", "ZELLE FROM", "PAYPAL TRANSFER IN", "CASH APP DEPOSIT", "MOBILE CHECK DEPOSIT"),
    RENT(Kind.HOUSING, "ZELLE TO RENT", "RENT PAYMENT APARTMENTS", "HOME MORTGAGE PAYMENT", "MTG PYMT", "PROPERTY MANAGEMENT RENT", "APTS RENT"),
    UTILITY(Kind.HOUSING, "ELECTRIC BILL PAYMENT", "ENERGY BILLPAY", "WATER UTILITY", "GAS COMPANY PAYMENT", "POWER CO AUTOPAY", "ELECTRIC AUTOPAY"),
    TELCO(Kind.HOUSING, "T-MOBILE AUTOPAY", "VERIZON WIRELESS PMT", "AT&T WIRELESS AUTOPAY", "CRICKET WIRELESS", "MINT MOBILE", "COMCAST XFINITY INTERNET"),
    LOAN_PAYMENT(Kind.OBLIGATION, "AUTO LOAN PAYMENT", "FINANCIAL LOAN PMT", "INSTALLMENT PAYMENT", "STUDENT LOAN SERVICING", "PERSONAL LOAN ACH", "AFFIRM INC INSTALLMENT"),
    CARD_PAYMENT(Kind.OBLIGATION, "CREDIT CARD PAYMENT", "CARD AUTOPAY", "CARD PMT", "DISCOVER CARD PAYMENT", "CAPITAL ONE CARD PMT", "CHASE CARD AUTOPAY"),
    GROCERY(Kind.ESSENTIAL, "WALMART SUPERCENTER", "KROGER", "ALDI", "COSTCO WHSE", "TRADER JOES", "SAFEWAY", "H-E-B"),
    HEALTH(Kind.ESSENTIAL, "CVS PHARMACY", "WALGREENS", "MEDICAL CENTER COPAY", "DENTAL CLINIC"),
    DINING(Kind.DISCRETIONARY, "DOORDASH ORDER", "UBER EATS", "STARBUCKS", "CHIPOTLE", "MCDONALDS", "RESTAURANT"),
    ENTERTAINMENT(Kind.DISCRETIONARY, "AMC THEATRES", "TICKETMASTER", "STEAM PURCHASE", "AMAZON MKTPLACE", "PLAYSTATION NETWORK", "BEST BUY"),
    SUBSCRIPTION(Kind.DISCRETIONARY, "NETFLIX.COM", "SPOTIFY USA", "HULU", "APPLE.COM/BILL", "DISNEY PLUS", "GYM MEMBERSHIP"),
    TRAVEL(Kind.DISCRETIONARY, "DELTA AIR LINES", "AIRBNB", "MARRIOTT", "UBER TRIP", "SHELL OIL", "CHEVRON GAS"),
    GAMBLING(Kind.RISK, "DRAFTKINGS DEPOSIT", "FANDUEL SPORTSBOOK", "BETMGM ONLINE", "CASINO ATM", "LOTTERY ONLINE"),
    NSF_FEE(Kind.RISK, "NSF RETURNED ITEM FEE", "OVERDRAFT FEE", "INSUFFICIENT FUNDS CHARGE", "RETURNED PAYMENT FEE"),
    ATM_CASH(Kind.OTHER, "ATM WITHDRAWAL", "CASH WITHDRAWAL", "ATM CASH 7-ELEVEN"),
    TRANSFER_OUT(Kind.OTHER, "TRANSFER TO SAVINGS", "ZELLE TO FRIEND", "PAYPAL TRANSFER OUT", "VENMO PAYMENT"),
    OTHER(Kind.OTHER, "MISC DEBIT", "PURCHASE", "POS DEBIT");

    public enum Kind { INCOME, HOUSING, OBLIGATION, ESSENTIAL, DISCRETIONARY, RISK, OTHER }

    private final Kind kind;
    private final List<String> exemplars;

    TransactionCategory(Kind kind, String... exemplars) {
        this.kind = kind;
        this.exemplars = List.of(exemplars);
    }

    public Kind kind() {
        return kind;
    }

    public List<String> exemplars() {
        return exemplars;
    }

    public boolean isIncome() {
        return kind == Kind.INCOME;
    }
}
